# Generated by Django 5.1.7 on 2025-05-03 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ["id"],
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки",
                verbose_name="Признак публичности",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_useful_habit",
            field=models.BooleanField(
                default=False,
                help_text="Признак приятной привычки",
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="location",
            field=models.CharField(
                default="Дома",
                help_text="Место, где выполнять привычку",
                max_length=250,
                verbose_name="Место",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                help_text="Периодичность выполнения привычки (для напоминания), в днях",
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Привычка, которая связана с другой привычкой, важно указывать для полезных привычек",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Вознаграждение после выполнения",
                max_length=200,
                null=True,
                verbose_name="Вознаграждение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                help_text="Время, когда выполнять привычку", verbose_name="Время"
            ),
        ),
    ]
